Traceback (most recent call last):
  File "/Users/cancerm/anaconda3/envs/py3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/cancerm/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/cancerm/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/cancerm/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/cancerm/anaconda3/envs/py3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/cancerm/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/cancerm/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/cancerm/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/var/folders/tn/n1z0j1bd5dscgy74hj1mn2nh0000gn/T/ipykernel_92276/2843662873.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mfrom[0m [0mtorch[0m [0;32mimport[0m [0mnn[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mfrom[0m [0mtorch[0m[0;34m.[0m[0mutils[0m[0;34m.[0m[0mdata[0m [0;32mimport[0m [0mDataLoader[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0;32mfrom[0m [0mtorchvision[0m [0;32mimport[0m [0mdatasets[0m[0;34m,[0m [0mtransforms[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mModuleNotFoundError[0m: No module named 'torchvision'
ModuleNotFoundError: No module named 'torchvision'

