Traceback (most recent call last):
  File "/Users/didi/opt/anaconda3/envs/py3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/didi/opt/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/didi/opt/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/didi/opt/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/didi/opt/anaconda3/envs/py3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/didi/opt/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/didi/opt/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/didi/opt/anaconda3/envs/py3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
arr = [2, 1, 4, 6, 5]

quick_sort(arr)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRecursionError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-3-3bdc118f8fe9>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0marr[0m [0;34m=[0m [0;34m[[0m[0;36m2[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m4[0m[0;34m,[0m [0;36m6[0m[0;34m,[0m [0;36m5[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0mquick_sort[0m[0;34m([0m[0marr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-2-6fddb58b921b>[0m in [0;36mquick_sort[0;34m(arr, left, right)[0m
[1;32m     23[0m             [0marr[0m [0;34m=[0m [0mswap[0m[0;34m([0m[0marr[0m[0;34m,[0m [0mi[0m[0;34m,[0m [0mpivot[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m [0;34m[0m[0m
[0;32m---> 25[0;31m     [0mquick_sort[0m[0;34m([0m[0marr[0m[0;34m,[0m [0mleft[0m[0;34m,[0m [0mpivot[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     26[0m     [0mquick_sort[0m[0;34m([0m[0marr[0m[0;34m,[0m [0mpivot[0m [0;34m+[0m [0;36m1[0m[0;34m,[0m [0mright[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     27[0m [0;34m[0m[0m

... last 1 frames repeated, from the frame below ...

[0;32m<ipython-input-2-6fddb58b921b>[0m in [0;36mquick_sort[0;34m(arr, left, right)[0m
[1;32m     23[0m             [0marr[0m [0;34m=[0m [0mswap[0m[0;34m([0m[0marr[0m[0;34m,[0m [0mi[0m[0;34m,[0m [0mpivot[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m [0;34m[0m[0m
[0;32m---> 25[0;31m     [0mquick_sort[0m[0;34m([0m[0marr[0m[0;34m,[0m [0mleft[0m[0;34m,[0m [0mpivot[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     26[0m     [0mquick_sort[0m[0;34m([0m[0marr[0m[0;34m,[0m [0mpivot[0m [0;34m+[0m [0;36m1[0m[0;34m,[0m [0mright[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     27[0m [0;34m[0m[0m

[0;31mRecursionError[0m: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object

